// Monday.com GraphQL API helpers — New Leads Board (18415182819) in CRM workspace
// Confirmed column IDs via API introspection 2026-05-28:
//   dropdown_mm3snqy  → Lead Source (dropdown)
//   date_mm3s69gh     → Lead Received Date
//   color_mm3s6y9e    → Lead Status
//   text_mm3sz7t8     → Notes

const MONDAY_API = 'https://api.monday.com/v2';
const BOARD_ID   = process.env.MONDAY_BOARD_ID || '18415182819';

const COLUMN_IDS = {
  source: 'dropdown_mm3snqy',  // Lead Source (dropdown)
  date:   'date_mm3s69gh',     // Lead Received Date
  status: 'color_mm3s6y9e',    // Lead Status
  notes:  'text_mm3sz7t8',     // Notes
  phone:  'phone_mm3scxqp',    // Phone
  email:  'email_mm3sqwnf',    // Email
};

async function query(gql, variables = {}) {
  const resp = await fetch(MONDAY_API, {
    method: 'POST',
    headers: {
      'Content-Type':  'application/json',
      Authorization:   `Bearer ${process.env.MONDAY_API_KEY}`,
      'API-Version':   '2024-01',
    },
    body: JSON.stringify({ query: gql, variables }),
    signal: AbortSignal.timeout(20000),
  });
  const data = await resp.json();
  if (data.errors) throw new Error(`Monday error: ${JSON.stringify(data.errors)}`);
  return data.data;
}

// Create a new Leads item when a proposal is generated
export async function createProposalItem({ merchantName, businessType, template, customRate, salesperson, proposalUrl }) {
  if (!process.env.MONDAY_API_KEY) return null;

  const today = new Date().toISOString().slice(0, 10);
  const columnValues = JSON.stringify({
    [COLUMN_IDS.source]: { labels: ['Sales Proposal'] },
    [COLUMN_IDS.date]:   { date: today },
    [COLUMN_IDS.status]: { label: 'New' },
  });

  const data = await query(`
    mutation ($boardId: ID!, $itemName: String!, $columnValues: JSON!) {
      create_item(board_id: $boardId, item_name: $itemName, column_values: $columnValues, create_labels_if_missing: true) {
        id
        name
      }
    }
  `, { boardId: BOARD_ID, itemName: merchantName, columnValues });

  const itemId = data?.create_item?.id || null;

  if (itemId) {
    await addActivityNote(itemId,
      `📋 Proposal generated by ${salesperson || 'UrPay Team'}\n` +
      `Business: ${businessType} · Template: ${template} · Rate: ${customRate || 'Standard'}\n` +
      `Link: ${proposalUrl}`
    );
  }

  return itemId;
}

// Proposal engagement is tracked via activity notes in proposals/track.js — Lead Source stays as Sales Proposal
export async function updateProposalStatus(_itemId, _event) {}

// Add an activity note to a Leads item
export async function addActivityNote(itemId, note) {
  if (!itemId || !process.env.MONDAY_API_KEY) return;
  await query(`
    mutation ($itemId: ID!, $value: String!) {
      create_update(item_id: $itemId, body: $value) { id }
    }
  `, { itemId: String(itemId), value: note });
}

// Source label map for inbound leads
const SOURCE_LABELS = {
  contact:  'Website',
  partner:  'Website',
  dev:      'Website',
  chatbot:  'Website Chatbot',
  joe:      'AI Joe (1800)',
};

// Create a Leads item for an inbound enquiry (website forms, chatbot, JOE)
export async function createInboundLead({ name, email, phone, business, formType, groupLabel, message }) {
  if (!process.env.MONDAY_API_KEY) return null;

  const itemName = business || name || 'Website Enquiry';
  const today    = new Date().toISOString().slice(0, 10);
  const source   = SOURCE_LABELS[formType] || 'Website';

  const noteParts = [
    name       && `Name: ${name}`,
    phone      && `Phone: ${phone}`,
    email      && `Email: ${email}`,
    business   && `Business: ${business}`,
    groupLabel && `Enquiry type: ${groupLabel}`,
  ].filter(Boolean).join(' · ');

  const columnValues = JSON.stringify({
    [COLUMN_IDS.source]: { labels: [source] },
    [COLUMN_IDS.date]:   { date: today },
    [COLUMN_IDS.status]: { label: 'New' },
    ...(phone && { [COLUMN_IDS.phone]: { phone, countryShortName: 'AU' } }),
    ...(email && { [COLUMN_IDS.email]: { email, text: email } }),
    ...(noteParts && { [COLUMN_IDS.notes]: noteParts }),
  });

  const data = await query(`
    mutation ($boardId: ID!, $itemName: String!, $columnValues: JSON!) {
      create_item(board_id: $boardId, item_name: $itemName, column_values: $columnValues, create_labels_if_missing: true) {
        id name
      }
    }
  `, { boardId: BOARD_ID, itemName, columnValues });

  const itemId = data?.create_item?.id || null;

  if (itemId) {
    const lines = [
      `📥 Inbound lead — ${source}`,
      `Name: ${name || '—'}`,
      business   && `Business: ${business}`,
      email      && `Email: ${email}`,
      phone      && `Phone: ${phone}`,
      groupLabel && `Enquiry type: ${groupLabel}`,
      message    && `\nMessage:\n${message}`,
    ].filter(Boolean).join('\n');
    await addActivityNote(itemId, lines);
  }

  return itemId;
}
