// Monday.com GraphQL API helpers — Leads board (18402268257)
// Confirmed column IDs via API introspection 2026-05-28:
//   lead_status      → Status
//   lead_company     → Company
//   lead_email       → Email
//   lead_phone       → Phone
//   color_mkyb8krc   → Lead Source
//   date__1          → Last interaction

const MONDAY_API  = 'https://api.monday.com/v2';
const BOARD_ID    = process.env.MONDAY_BOARD_ID || '18402268257';

const COLUMN_IDS = {
  status:  'lead_status',
  company: 'lead_company',
  email:   'lead_email',
  phone:   'lead_phone',
  source:  'color_mkyb8krc',
  date:    'date__1',
};

async function query(gql, variables = {}) {
  const resp = await fetch(MONDAY_API, {
    method: 'POST',
    headers: {
      'Content-Type':  'application/json',
      Authorization:   `Bearer ${process.env.MONDAY_API_KEY}`,
      'API-Version':   '2024-01',
    },
    body: JSON.stringify({ query: gql, variables }),
    signal: AbortSignal.timeout(10000),
  });
  const data = await resp.json();
  if (data.errors) throw new Error(`Monday error: ${JSON.stringify(data.errors)}`);
  return data.data;
}

// Create a new Leads item when a proposal is generated
export async function createProposalItem({ merchantName, businessType, template, customRate, salesperson, proposalUrl }) {
  if (!process.env.MONDAY_API_KEY) return null;

  const today = new Date().toISOString().slice(0, 10);
  const columnValues = JSON.stringify({
    [COLUMN_IDS.company]: merchantName,
    [COLUMN_IDS.source]:  { label: 'Sales Proposal' },
    [COLUMN_IDS.date]:    { date: today },
  });

  const data = await query(`
    mutation ($boardId: ID!, $itemName: String!, $columnValues: JSON!) {
      create_item(board_id: $boardId, item_name: $itemName, column_values: $columnValues) {
        id
        name
      }
    }
  `, { boardId: BOARD_ID, itemName: merchantName, columnValues });

  const itemId = data?.create_item?.id || null;

  // Post first activity note with full proposal context
  if (itemId) {
    await addActivityNote(itemId,
      `📋 Proposal generated by ${salesperson || 'UrPay Team'}\n` +
      `Business: ${businessType} · Template: ${template} · Rate: ${customRate || 'Standard'}\n` +
      `Link: ${proposalUrl}`
    );
  }

  return itemId;
}

// Update Lead Source status when proposal is opened or PDF downloaded
export async function updateProposalStatus(itemId, event) {
  if (!itemId || !process.env.MONDAY_API_KEY) return;

  const label =
    event === 'pdf_download' ? 'PDF Downloaded' :
    event === 'cta_click'    ? 'CTA Clicked'    :
                               'Proposal Opened';

  try {
    await query(`
      mutation ($boardId: ID!, $itemId: ID!, $columnId: String!, $value: JSON!) {
        change_column_value(board_id: $boardId, item_id: $itemId, column_id: $columnId, value: $value) {
          id
        }
      }
    `, {
      boardId:  BOARD_ID,
      itemId:   String(itemId),
      columnId: COLUMN_IDS.source,
      value:    JSON.stringify({ label }),
    });
  } catch {
    // Status label may not exist in board — activity note is the primary record
  }
}

// Add an activity note to a Leads item
export async function addActivityNote(itemId, note) {
  if (!itemId || !process.env.MONDAY_API_KEY) return;
  await query(`
    mutation ($itemId: ID!, $value: String!) {
      create_update(item_id: $itemId, body: $value) { id }
    }
  `, { itemId: String(itemId), value: note });
}

// Source label map for inbound leads
const SOURCE_LABELS = {
  contact:  'Website Contact Form',
  partner:  'Website Partner Form',
  dev:      'Website Dev / API Form',
  chatbot:  'Website Chatbot',
  joe:      'AI Joe (1800)',
};

// Create a Leads item for an inbound enquiry (website forms, chatbot, JOE)
export async function createInboundLead({ name, email, phone, business, formType, groupLabel, message }) {
  if (!process.env.MONDAY_API_KEY) return null;

  const itemName = business || name || 'Website Enquiry';
  const today    = new Date().toISOString().slice(0, 10);
  const source   = SOURCE_LABELS[formType] || 'Website';

  const columnValues = JSON.stringify({
    [COLUMN_IDS.company]: itemName,
    ...(email && { [COLUMN_IDS.email]: { email, text: email } }),
    ...(phone && { [COLUMN_IDS.phone]: { phone, countryShortName: 'AU' } }),
    [COLUMN_IDS.source]:  { label: source },
    [COLUMN_IDS.date]:    { date: today },
  });

  const data = await query(`
    mutation ($boardId: ID!, $itemName: String!, $columnValues: JSON!) {
      create_item(board_id: $boardId, item_name: $itemName, column_values: $columnValues) {
        id name
      }
    }
  `, { boardId: BOARD_ID, itemName, columnValues });

  const itemId = data?.create_item?.id || null;

  if (itemId) {
    const lines = [
      `📥 Inbound lead — ${source}`,
      `Name: ${name || '—'}`,
      business && `Business: ${business}`,
      email    && `Email: ${email}`,
      phone    && `Phone: ${phone}`,
      groupLabel && `Enquiry type: ${groupLabel}`,
      message  && `\nMessage:\n${message}`,
    ].filter(Boolean).join('\n');
    await addActivityNote(itemId, lines);
  }

  return itemId;
}
